# Generated by Django 4.2.3 on 2024-01-04 08:18

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Kategorilerin sıralanması için buradan sıra numarası verilmesi gerekiyor.",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_tr", models.CharField(max_length=100, null=True)),
                ("name_en", models.CharField(max_length=100, null=True)),
                ("name_ar", models.CharField(max_length=100, null=True)),
                ("categoryData", models.CharField(max_length=100)),
                ("menuData", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategoriler",
                "db_table": "Kategori",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="SauceModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Kategorilerin sıralanması için buradan sıra numarası verilmesi gerekiyor.",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_tr", models.CharField(max_length=100, null=True)),
                ("name_en", models.CharField(max_length=100, null=True)),
                ("name_ar", models.CharField(max_length=100, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
            options={
                "verbose_name": "Sos",
                "verbose_name_plural": "Soslar",
                "db_table": "Sos",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="MenuModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format="WEBP",
                        keep_meta=True,
                        null=True,
                        quality=100,
                        scale=None,
                        size=[1920, 1080],
                        upload_to="menu_images",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Menülerin sıralanması için buradan sıra numarası verilmesi gerekiyor.",
                    ),
                ),
                ("gluten", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100)),
                ("name_tr", models.CharField(max_length=100, null=True)),
                ("name_en", models.CharField(max_length=100, null=True)),
                ("name_ar", models.CharField(max_length=100, null=True)),
                ("content", models.TextField(blank=True, max_length=500)),
                ("content_tr", models.TextField(blank=True, max_length=500, null=True)),
                ("content_en", models.TextField(blank=True, max_length=500, null=True)),
                ("content_ar", models.TextField(blank=True, max_length=500, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "cookingTime",
                    models.IntegerField(
                        default=0, help_text="Menünün Hazırlanma süresini giriniz."
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu",
                        to="berweuli.categorymodel",
                    ),
                ),
                (
                    "souces",
                    models.ManyToManyField(
                        blank=True, related_name="souces", to="berweuli.saucemodel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Menü",
                "verbose_name_plural": "Menüler",
                "db_table": "Menü",
                "ordering": ("order",),
            },
        ),
    ]
