# Generated by Django 4.2.7 on 2023-12-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berweuli', '0002_menumodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='content_ar',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='menumodel',
            name='content_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='menumodel',
            name='content_tr',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='menumodel',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menumodel',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menumodel',
            name='name_tr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
