# Generated by Django 4.2.7 on 2023-12-02 08:43

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('berweuli', '0003_menumodel_content_ar_menumodel_content_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[465, 359], upload_to='menu_images'),
        ),
    ]
