# Generated by Django 4.2.7 on 2023-12-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berweuli', '0006_alter_menumodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SauceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Kategorilerin sıralanması için buradan sıra numarası verilmesi gerekiyor.')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Sos',
                'verbose_name_plural': 'Soslar',
                'db_table': 'Sos',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='menumodel',
            name='souces',
            field=models.ManyToManyField(related_name='souces', to='berweuli.saucemodel'),
        ),
    ]
