# Generated by Django 4.2.7 on 2023-12-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berweuli', '0007_saucemodel_menumodel_souces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='souces',
            field=models.ManyToManyField(blank=True, related_name='souces', to='berweuli.saucemodel'),
        ),
    ]
