# Generated by Django 4.2.7 on 2023-12-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berweuli', '0008_alter_menumodel_souces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='slug',
        ),
    ]
