# Generated by Django 4.2.7 on 2023-12-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berweuli', '0009_remove_categorymodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='name_tr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
