# Generated by Django 4.2.7 on 2023-12-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berweuli', '0010_categorymodel_name_ar_categorymodel_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saucemodel',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saucemodel',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saucemodel',
            name='name_tr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
